### ISSUE TITLE
Really lost.

### ISSUE THREAD

**Issue by theflexa1** [SmartEVSE/SmartEVSE-3#10]
Hello to everyone.

I blought one SmartEVSE 3.0 and installed my self. All went perfect but the bad news came when I saw that my solar battery was charging my cars battery...

I ask Michael Stegen for help and sed me here. I now how to update de firmware of my EVSE, but I am a little bit lost in how to make this battery use to stop. My knowlage in coding and APIs is very small... So I am asking for a little bit of help.

I don´t know if I need a HA, but I have a NAS.

Thank you.

**Comment by rvdgaag** [comment]
Have a look here:

https://github.com/serkri/SmartEVSE-3/releases/tag/v1.1.0-serkri-v3
