### ISSUE TITLE
Locking actuator unlocks when full

### ISSUE THREAD

**Issue by nickF007** [SmartEVSE/SmartEVSE-3#13]
I have a SmartEVSE v3 with a RFID tag reader and sensorbox v2. Everything works verry well! It would be nice if the actuator stays locked when the car is done charging and then unlocks with the RFID.
Step 1 put in cable
Step 2 Read card
Step 3 Lock cable/charge
Step 4 Done charging/stop charging
Step 5 Read card
Step 6 Stop charging/unlock cable

Something like this? If it’s already possible witch option do I need? 
Thank you verry much for all you’re effort.

**Comment by mstegen** [comment]
If you set the RFID option to "EnableOne" It should keep the cable locked, until you present the RFID card again.
