### ISSUE TITLE
Menu item missing for MainsMeterMeasure ?

### ISSUE THREAD

**Issue by fluppie** [SmartEVSE/SmartEVSE-3#16]
Hi @mstegen,

I was browsing the code and think I've found a bug. When telling SmartEVSE what the mainsmeter is measuring, you only have two options/values in the menu, "All" and "Home+EVSE", while I think the code works/expects to work with 3 options/values.

Here you see the 2 options in the menu:
https://github.com/SmartEVSE/SmartEVSE-3/blob/c7c0ca81f03f97c1ba22a9f8a0a97deeeb02fe74/SmartEVSE-3/src/evse.cpp#L1382-L1384

Here you see 3 options:
0: Mains (Home+EVSE+PV) / 1: Home+EVSE / 2: Home
https://github.com/SmartEVSE/SmartEVSE-3/blob/c7c0ca81f03f97c1ba22a9f8a0a97deeeb02fe74/SmartEVSE-3/src/evse.cpp#L122

I also want to understand it right. I have 3 SMD230 meters, one which measures more or less the same than the kWh meter from the power company, so everything. Another one measuring every kWh that goes into the EV. And a last one that keeps track of the kWh produced by the solar PV system.

When choosing option All, it sets MainsMeterMeasure to 0. Which I think is right, but then it disables the PV Meter and PV Meter settings. or I misunderstand the whole thing, or some menu settings was forgotten when solar mode was developed?
Also the SDM230 meter don't report a negative current. They only report negative power in Watt and a negative cos phi when there is solar production (on the PV meter) and the mains meter cos phi get's negative when injecting into the grid.

Current of the meter that measures the same as the power company:
![afbeelding](https://user-images.githubusercontent.com/8402106/166124562-6eae5ccb-bd1a-47bf-9b27-181c0d4cb35a.png)

Power of the meter that measures the same as the power company:
![afbeelding](https://user-images.githubusercontent.com/8402106/166124576-a8201be3-d031-4e53-95e1-dbfae8e82dee.png)

Cos phi of the meter that measures the same as the power company:
![afbeelding](https://user-images.githubusercontent.com/8402106/166124619-c141149b-b305-4bf5-be7b-67f8c36d75e7.png)

**Comment by mstegen** [comment]
Hi,

The mainsmeter options were developed by @bobosch with a specific use case in mind. If i remember correctly the Home+EVSE option measures everything except PV which is fed into the grid -before- this meter.


```Possible positions of electric meter:

 Home
   |
  (C)
   |
   +--[SUPPLY]--(F)--+--(E)--[CABLE]-- Car 1 [MIN]-[MAX]
   |                 +--(E)--[CABLE]-- Car 2 [MIN]-[MAX]
  (B)
   |
   +------------(D)------------------- PV
   |
  (A)
   |
[MAINS]

(X): electric meter
[XXX]: current limitation


Configuration

- Main electric meter (reduces charging current in smart mode)
  - Type [None* / Sensorbox / Finder / Phoenix Contact]
  - Measures [Mains (A) / Home with EVSE (B) / Home without EVSE (C)]
```
You are right there was the option 'Home without EVSE' in the original idea, but never implemented.

I think in your use case you can just use the one SDM230 that is in series with your official energy meter, and one that measures the EV power/energy. 
There is no need to have a seperate PV meter.

The code will take the Power and Voltage measurements of your SDM230 and use that to calculate the current.

**Comment by bobosch** [comment]
Hi! Yes, "All" is correct when the EM is placed in the same position as the EM from the power company. Then it must be able to detect the current direction. Some EMs always reports positive current values (Eastron as well), this works only with the predefined EMs. Therefore multiple registers are considered:
https://github.com/SmartEVSE/SmartEVSE-2/blob/ef703d897320e47cfccbcc3e98c45c7c4e7411f4/SmartEVSE2.X/modbus.c#L583-L594
https://github.com/SmartEVSE/SmartEVSE-2/blob/ef703d897320e47cfccbcc3e98c45c7c4e7411f4/SmartEVSE2.X/modbus.c#L722-L728

**Comment by dingo35** [comment]
I took the liberty to remove this code because it turned out to be of no use to anyone...
