### ISSUE TITLE
Solaredge meter issue

### ISSUE THREAD

**Issue by elas00** [SmartEVSE/SmartEVSE-3#23]
Connected to solaredge 3 phase inverter, shows - 3277A, main meter configured as solaredge.
![IMG_20220709_120542](https://user-images.githubusercontent.com/108978973/178102133-3e253746-0e55-4429-83e4-a0ff56ff7b6f.jpg)

Any solution?

**Comment by bobosch** [comment]
The Solaredge inverter uses other modbus registers than the Solaredge meter.
https://www.solaredge.com/sites/default/files/sunspec-implementation-technical-note.pdf
Try custom electric meter with the settings
"BYTE ORD" HBF & HWF (Byte order of custom electric meter)
"DATATYPE" 3 (Data type of custom electric meter)
"FUNCTION" INT16 (Modbus Function of custom electric meter)
"CUR REGI" 40072 (Register for Current (A) of custom electric meter)
"CUR DIVI" 1 (Divisor for Current (A) of custom electric meter)

**Comment by bobosch** [comment]
But it will only measure the PV generation? So it will only show the PV current, but SmartEVSE will not work as expected as it needs the current from Mains

**Comment by elas00** [comment]
Solaredge inverter measure mains via inepro r380 connected via modbus and is working fine on solaredge app.

**Comment by bobosch** [comment]
Does the value -3277A change or is it always the same? Nevertheless please try custom EM. You can hold the button to fast change the settings. And going backwards will be a little bit faster because highest value is 65530 so only 25500 to reduce :-( Or use serial console.

**Comment by elas00** [comment]
Value was always the same, now work ok with mains meter configured as solaredge.
![IMG_20220711_123941](https://user-images.githubusercontent.com/108978973/178247046-837d00a4-1828-48c9-aa60-5c2cb7bce93c.jpg)

**Comment by devdems** [comment]
@elas00 can you tell how you connected the charger to SolarEdge to get the data from the InePro meter?
