### ISSUE TITLE
EVSE contactor not opening after terminating the charging process

### ISSUE THREAD

**Issue by BitterAndReal** [SmartEVSE/SmartEVSE-3#26]
If I'm terminating the charging process from the EV (6) and the EV charge controller indicates State B (disconnecting the R2 resistor) the smart EVSE V3 does not open the AC contactor (9b). 
Meanwhile the EV unlocks the plug (9a) and the user can disconnect the plug **while there is still power on the plug**. 
The AC contactor only opens once I remove AC to the EVSE.
We did not have this issue with the smart EVSE V2.2.

![IEC61851 charging sequence-01](https://user-images.githubusercontent.com/34364368/182866882-7f9b1bc5-acc9-40e9-bf92-ec16feff3e11.png)

I have not checked what happens when I terminate the charging process from the EVSE.

**Comment by mstegen** [comment]
Please check the contactor type, the SmartEVSE v3's SSRs that switch the contactors on/off, don't work well with humm free/ silent contactors. 
Once switched on, they then will then not switch off anymore (although the SmartEVSE has switched off the contactor)

The Iskra IKA432-40 and Hager ESC425 work good with the SmartEVSE.

**Comment by BitterAndReal** [comment]
Thanks for your explanation.
We are using quite big 4P 100A contactors.
I guess the quickest solution for now is to place a control relais between the EVSE output and the contactor...
