### ISSUE TITLE
EVSE Status register

### ISSUE THREAD

**Issue by dummyka9609** [SmartEVSE/SmartEVSE-3#27]
Hi!
I couldn't find anywhere the meaning of the possible states of the status register (0x0000).
Can anyone tell me where can i find?

**Comment by bobosch** [comment]
https://github.com/SmartEVSE/SmartEVSE-2#modbus

**Comment by dummyka9609** [comment]
I found that too, thanks. But I don't know what it mean _"A-D (EVSE State), E-H (A-D Waiting for Balance Master)"_
[Here](https://github.com/SmartEVSE/SmartEVSE-3/issues/1) mstegen wrote how I can start the charging via modbus, but I would like to know what each state means exactly.

**Comment by bobosch** [comment]
I think the documentation is out of date here. It should return the State as defined in the code:
https://github.com/SmartEVSE/SmartEVSE-3/blob/a91b47bc5032908e46739e2b390bf2171d890706/SmartEVSE-3/include/evse.h#L139-L149

**Comment by bobosch** [comment]
Updated README.md (https://github.com/SmartEVSE/SmartEVSE-2/commit/d3263b789483d5297697f0b53ef506fd54d82847)
