### ISSUE TITLE
Crashes when charging Renault Zoe

### ISSUE THREAD

**Issue by Xnygra** [SmartEVSE/SmartEVSE-3#29]
Having used a SmartEvse V2 for many years, I bought a V3 and replaced my V2. It works on all EV that I tried, but the EVSE crashes when charging Renault Zoe, and the SmartEvse needs to be Power Cycled to work again. 

Having the Mains set to 20A and MAX to 16A. House is typically drawing 5A. 3-phase. When start charge all currents from the sensorbox freezes to a value, typically 9A, and the charing do not start. To get the SmartEvse to work again I have to kill its power to restart it. 

When lower the MAX to 12A, so the EVSE don't need to limit the charge Amps (from the sensorbox readings) it works fine. 

So my workaround is to have a lower MAX charge amp, so it dont need to lower the charge amp based on the sensor box. And again, this only happens to renault Zoe (tested on two vehicles) and not on any vehicles from the VAG group or Hyundai/Kia. Or switch back to the old V2

Im not a coder my self, so I'm a bit lost here, but happy to help with more data/information that might be required to find what's going wrong?

**Comment by mstegen** [comment]
Hi, 
What brand of contactor are you using? I've noticed that some contactors will disturb the controller, up to a point where the controller crashes.

**Comment by Xnygra** [comment]
I'm using a GE CTX 32A. I got a Schneider sitting at home that i can swap to, to see if that makes any difference.

**Comment by Xnygra** [comment]
Swapped to a Schneider contactor, and it seems to work now. Still a bit confused why that solved the problem and why it seems only happens with Zoes.

**Comment by mstegen** [comment]
I'm glad you fixed the issue, i agree that it's weird that the GE contactor only with a Zoe causes the issue..
