### ISSUE TITLE
spiffs.bin FAIL on upload

### ISSUE THREAD

**Issue by deqw** [SmartEVSE/SmartEVSE-3#31]
When trying to upload the 23 Mar 2022 release spiffs.bin file the upload results in 'FAIL'. The firmware itself uploads fine, but no /settings or any other response.

**Comment by brammb** [comment]
I have the same issue

**Comment by dingo35** [comment]
The problem might be renamed files; make sure you upload ONLY files named _exactly_  "firmware.bin" and "spiffs.bin", since the firmware checks for those names!
