### ISSUE TITLE
Support for simplified mode 3 charging

### ISSUE THREAD

**Issue by allardpost** [SmartEVSE/SmartEVSE-3#32]
Hi, my “old” smartEVSE v1(?) does not seem to be able to use the mode3 simplified charge protocol (as described here https://www.iqlaad.com/knowledge-base/fundamentals/using-mode-3-simplified-for-non-adaptive-loads/). Is it implemented on V3 or are there plans to implement it?

**Comment by mstegen** [comment]
That is correct, i only support a transition through state B. So it has to go from A to B first (connected to EV) before energizing (State B -> state C) 
There are no plans to implement it.
