### ISSUE TITLE
manual: missing information about operational temperature range

### ISSUE THREAD

**Issue by poki123** [SmartEVSE/SmartEVSE-3#37]
Hello, I am interested about EVSE unit, but I can't find any information about the operational temperature range (eg. -20°C  to +60°C ??). Could you provide this info, please?

Thank you

**Comment by mstegen** [comment]
The operating temperature is indeed -20°C to +60°C. At 65°C (internal temperature) the charging will stop, and the temperature has to drop to 55°C again to resume charging.
