### ISSUE TITLE
Upgrade from v2

### ISSUE THREAD

**Issue by martijndierckx** [SmartEVSE/SmartEVSE-3#4]
Is the RCM compatible with the one I purchased for v2?

**Comment by wbitholedotbe** [comment]
Yes... It's the same.

**Comment by mstegen** [comment]
Yes you can plug it in P1 (the white socket) on the SmartEVSE v3. It's not possible anymore to manually connect it to the 12 pin pluggable connector

**Comment by bostjanlaba** [comment]
Is the main controller v3 different than v2? Can I upgrade v2 to work with wifi or do I need to purchase v3?

**Comment by bobosch** [comment]
Yes, v2 is a different controller without WiFi

**Comment by pascalsaul-copaco** [comment]
Can you also upgrade a v2 controller with the v3 software?

**Comment by Ferforfaen** [comment]
I have just upgraded my V2 to a V3 (bought the V3 from Stegen) But to my suprise, my old sensor box does not work with the V3 hardware. Is this a known issue? Not keen to buy a sensorbox V2 as my old one works fine for my needs.

**Comment by pascalsaul** [comment]
Can you also upgrade a v2 controller with the v3 software?

**Comment by zharijs** [comment]
> Can you also upgrade a v2 controller with the v3 software?

Short:  No.

Long:

v2 runs on Microchip PIC MCU, v3 uses Esperessif ESP32 - one is small 8 bit MCU, other is dual-core 32bit SoC. The code base is radically different. Parts that are the same, are "software" things like menu, display commands, modbus protocol, but all hardware access, times, ADC access, port and peripheral access are different. 

Also, v2 using PIC, uses Microchip MPLab-X to IDE, ESP32 variant uses Arduino framework on top of PlatformIO on top of VSCode. So the toolchain is radically different too. 

So v3 software is what you would call a "port" of v2 software - soft parts are the same, hardware access and low level functionality is completely different.

**Comment by mstegen** [comment]
Thanks @zharijs for the thorough explanation.

To reply to the question of @Ferforfaen , the protocol used on the sensorbox changed to modbus. You can reprogram the pic chip in the sensorbox 1 to make it compatible with SmartEVSE v3 (or SmartEVSE v2 with new software)
https://github.com/SmartEVSE/Sensorbox-1

If you can not reprogram the software yourself, send it to me, and i'll reprogram it for you.

**Comment by avelinopepino** [comment]
Hi, I have a v2.12 SmartEvse with a sensorbox v1.5 and they work perfectly. I recently purchased a smartevse v3 and try to put it as master of the v2.12. It didn't work and as far as I know, I have to upgrade the v2.12. Is there any guidelines to do it for dummies?
Thanks in advance!

**Comment by avelinopepino** [comment]
The issue has been somveolvedd. Please try to correct the order of RX and TX pins that are informed on the website.
