### ISSUE TITLE
High incoming supply voltage

### ISSUE THREAD

**Issue by DariusPL** [SmartEVSE/SmartEVSE-3#45]
The home energy meter reports the incoming supply voltage in excess 250V consistently overnight, peaking at 256V in the middle of the day.  What behavior of SmartEVSE shall expect charging the EV while voltage peak up to 256V.
If the EV shutdowns charging and voltage restore to operational range 220-240v does the SmartEVSE will try to recover charging automatically.

**Comment by mstegen** [comment]
The SmartEVSE has no voltage measurement built in. Therefore it's impossible for it to react on overvoltage.
Please note that the absolute maximum voltage is 263Vac, above that the controller might become defective. There is a MOV for protecting against overvoltage spikes, this will start conducting around 275Vac, and might eventually blow the internal fuse.

The SmartEVSE will keep trying to start charging, if it detects a connected EV.
