### ISSUE TITLE
Firmware freeze in charge mode

### ISSUE THREAD

**Issue by minoseigenheer** [SmartEVSE/SmartEVSE-3#47]
We have an issue that sometimes the EVSE is frozen in charge mode even if the car has stoped the session and is disconnected.
The reset button is not working and we have to power cycle all EVSE's in the master / slave setup in the correct order to be able to charge again.
We never had this issue with V2.2 but with the V3.

**Comment by mstegen** [comment]
I have seen this happen a few times, where the contactor would introduce a EMP spike, somehow freezing the CPU on the controller. 
I would suggest to try a different contactor. The ISKRA types i sell don't have this issue.

**Comment by dingo35** [comment]
Closing topic because of inactivity.
