### ISSUE TITLE
sdp request

### ISSUE THREAD

**Issue by Fatih738** [SmartEVSE/SmartEVSE-3#49]
I have codico red carrier board. I have used stm32f4 to communicate with qca chip. I have used https://github.com/uhi22/ccs32clara. Can I make a ccs charge controller with this code. I know that I have to implement cp duty cycle and pp reading. How can I test stm32f4 and red carrier board as a pev side.
Also I have white carrier board EI. I have ran Seventax FreeV2G code. I have connected CP and PP pins to red carrier board. But I havent set connection between these modules. I have raspberry pi, 3 red carrier board, white carrier board EI. CAn you help me about testing ccs charge controller with these board? How can I test these boards

SLAC matching succesfull. Im using white carrierd board EI with freeV2G as evse side. stm32 and red carrier board as pev side.
/* our link-local IPv6 address. Todo: do we need to calculate this from the MAC? Or just use a "random"? /
/ For the moment, just use the address from the Win10 notebook, and change the last byte from 0x0e to 0x1e.
You wrote these comments in code (ipv6.c). Idont understand here. Can you explain
Also after slac matching succesfull. [SDP] initiating SDP request. I dont pass the [SDP] initiating SDP request. How can I do sdp

thanks

**Comment by Fatih738** [comment]
![image](https://github.com/SmartEVSE/SmartEVSE-3/assets/124864491/a2045a30-3786-47e3-b673-13034e199b98)

I have received these outputs over uart

thanks

**Comment by Fatih738** [comment]
![image](https://github.com/SmartEVSE/SmartEVSE-3/assets/124864491/493146d0-d690-4d2e-97bc-426e74ac40de)

**Comment by uhi22** [comment]
Seems the codico is crashing. You could try to use pyPLC as evse, this would make it possible to record a pcap trace, which would help analyzing the topic.

**Comment by Fatih738** [comment]
Can I run pyPLC on raspberry pi with codico(red-carrier-board-p)?

**Comment by uhi22** [comment]
Yes, the pyPLC runs on Raspberry, and according to the datasheet of the redbeet, it is compatible with the QCA linux driver. I never used this combination, but others did successfully.

**Comment by Fatih738** [comment]
Can I coontrol all charge process with pyPlc as pev side on raspberr pi

**Comment by uhi22** [comment]
Johu from openinverter forum uses a beaglebone successfully for real world charging. I use Raspberry for the light bulb demo charging. So the short anser is: yes.

**Comment by Fatih738** [comment]
I have changed pevmac with my mac adress in pyPlcHomeplug.py
run with "sudo python3 pyPlc.py" command
I m getting this error
what is the local mac
Also what is the cause of this error
thanks a lot for your supports
![image](https://github.com/SmartEVSE/SmartEVSE-3/assets/124864491/8afb60b0-01e0-443f-9181-db5b4cd735f6)

**Comment by Fatih738** [comment]
I have connected raspberry pi to qca7000(red-carrier-board-p) with spi lines. I didnt use the ethernet cable. I will not use because of cp pe pins in the real world charge process. right?

**Comment by uhi22** [comment]
Yes, you do not need the ethernet cable.
