### ISSUE TITLE
SmartEVSE with scheduler already available?

### ISSUE THREAD

**Issue by Fixh1** [SmartEVSE/SmartEVSE-3#53]
Hi,
Is there already a SmartEVSE-firmware with scheduler available? Or do I have to write one myself? :-(
I know the repos from Sekri, but I didn't see a scheduler in it. Are there other firmware repos?

Regards
Hans

**Comment by fluppie** [comment]
https://github.com/dingo35/SmartEVSE-3.5 :-)

**Comment by dingo35** [comment]
Current 3.6.0 has delayed charging in the webserver screen, look at https://github.com/SmartEVSE/SmartEVSE-3/blob/master/docs/operation.md  , paragraph "Simple Timer".
