### ISSUE TITLE
Device not accessible 

### ISSUE THREAD

**Issue by 12koen** [SmartEVSE/SmartEVSE-3#55]
**Describe the bug**
Device rarely accessible through web interface running firmware version 3.6.1. Last week it would take a day or so until device was reachable again but last days haven't been able to connect to it at all. Using HA addon but no connection there either. Device is pingable. Charging works as expected.

**Upload your config**
Cannot load config - will update if I can access the device again

**Upload a debug log**
See above

**To Reproduce**
1. Device running in Smart mode with sensorbox 2, issue was there before attachment of sensorbox.

**Expected behavior**
I have no way of reaching or resetting the device

**Screenshots**

**Comment by dingo35** [comment]
Pleasr upgrade to 3.6.2, its webserver is improved

**Comment by 12koen** [comment]
Where to find it? Latest released version still 3.6.1

**Comment by 12koen** [comment]
Seems more stable at 3.6.2, thanks for the update!

**Comment by mstegen** [comment]
Closing this now, thanks for your feedback.
