### ISSUE TITLE
Cannot change MQTT configuration

### ISSUE THREAD

**Issue by 12koen** [SmartEVSE/SmartEVSE-3#56]
**Describe the bug**
When changing the MQTT configuration details the interface gives confirmation but the configuration is not changed. Modified the password to the wrongly entered one and the device connects to the MQTT broker.

**Upload your config**
Currently having an issue with accessing the device - see other bug report. 

**Upload a debug log**
See above

**To Reproduce**
Running firmware 3.6.1.

**Expected behavior**
MQTT configuration is actually changed upon update and can also be made blank (interface provides error). 

**Screenshots**

**Comment by 12koen** [comment]
Issue resolved with 3.6.2 version, thanks!

**Comment by dingo35** [comment]
Thx for reporting back!
