### ISSUE TITLE
Wrong version in /update page?

### ISSUE THREAD

**Issue by ftamminga** [SmartEVSE/SmartEVSE-3#60]
The main page displays version v3.6.7, however, the /update page indicates that the current version is 3.6.2.

I installed 3.6.7 twice with the same result. Ctrl-F5 did not help either.

![evse1](https://github.com/user-attachments/assets/256fc22a-7a52-416e-86ba-c6d4bc6c8e4f)
![evse2](https://github.com/user-attachments/assets/d5c4795b-1293-4823-bb2c-12d0dc0c11c7)

**Comment by dingo35** [comment]
This is probably a caching problem in your browser.
Close your webpage, open the smartevse page, and then press "Update" button; does the problem still persist?

**Comment by ftamminga** [comment]
Ah, I understand what is going on. The displayed version is set as the session variable 'version' in the home page. If you the press the update button, the update page uses this session variable to display the version.
Anyone who would directly browse to the update page, will either get no version at all, or the version that happens to be the value at that moment. Personally, I think this is not the best way to retrieve the version data, but since I now know how it works, I can live with it.

**Comment by dingo35** [comment]
I agree its not the best way, but to fire an extra query to the SmartEVSE to prevent this mismatch seemed a bit "expensive" to me ...
