### ISSUE TITLE
Eagle files

### ISSUE THREAD

**Issue by wbitholedotbe** [SmartEVSE/SmartEVSE-3#7]
Any chance we can get the eagle files like v2? Would like to make some small modifications and build it myself. Thanks.

**Comment by mstegen** [comment]
Not right now, perhaps in half a year or so.
What small changes do you have in mind? I might be able to add them to v3.1 ;-)

**Comment by wbitholedotbe** [comment]
Would like to add at least one input / output. For extra control and/or sensors.

**Comment by ARandomOWL** [comment]
Checking in on this. Is there a reason to withhold the hardware design sources?
