### ISSUE TITLE
Mains phase currents exceeds capacity for 3 phase - no stop of charging

### ISSUE THREAD

**Issue by fhbonte** [SmartEVSE/SmartEVSE-3#71]
**Describe the bug**
The charging current seems not controlled to ensure that the total of all Mains phase currents does not exceed the Capacity setting on 3 phase (both in PWR share master/slave as PWR share disabled).
When running on 1 phase, when the Mains exceed Capacity setting, smartevse stopped charging.

**Upload your config**
{"version":"v3.6.10","serialnr": XXXX ,"mode":"SMART","mode_id":3,"car_connected":true,"wifi":{"status":" YYYY"},"evse":{"temp":26,"temp_max":65,"connected":true,"access":true,"mode":1,"loadbl":1,"pwm":1024,"solar_stop_timer":0,"state":"Charging Stopped","state_id":9,"error":"None","error_id":0,"rfid":"Not Installed"},"settings":{"charge_current":60,"override_current":0,"current_min":6,"current_max":16,"current_main":32,"current_max_circuit":20,"current_max_sum_mains":10,"max_sum_mains_time":0,"solar_max_import":0,"solar_start_current":6,"solar_stop_time":10,"enable_C2":"Always On","mains_meter":"API","starttime":0,"stoptime":0,"repeat":0},"mqtt":{"host":" ZZZ"},"home_battery":{"current":0,"last_update":0},"ev_meter":{"description":"API","address":12,"import_active_power":4.099999905,"total_kwh":1005.900024,"charged_kwh":1005.900024,"currents":{"TOTAL":179,"L1":59,"L2":60,"L3":60},"import_active_energy":1005.900024,"export_active_energy":0},"mains_meter":{"import_active_energy":0,"export_active_energy":0},"phase_currents":{"TOTAL":215,"L1":65,"L2":88,"L3":62,"last_data_update":1733693994,"original_data":{"TOTAL":215,"L1":65,"L2":88,"L3":62}},"backlight":{"timer":118,"status":"ON"}}

**To Reproduce**
1. What Mode are you in? Smart 
2. What steps do you take so the problem arises? set via MQTT SmartEVSE-XXXX/Set/CurrentMaxSumMains between 10A and 96A.

**Expected behavior**
Total SumMains however stays at ~22A. While setting CurrentMaxSumMains = 10A, no stopping of charging while expected that charging should stop (as is the case for 1 phase).

**Comment by dingo35** [comment]
Please only do bug reports on the latest version, v3.7.2 .
